# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ExtUtils-MakeMaker-Coverage
version:      0.05
version_from: lib/ExtUtils/MakeMaker/Coverage.pm
installdirs:  site
requires:
    Devel::Cover:                  0
    Object::Accessor:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.27
